apiVersion: v1
kind: Pod
metadata:
  name: server1
  labels:
    tier: frontend
spec:
  containers:
  - name: hello1
    image: docker.io/nirgeier/nodejs-server1

---

apiVersion: v1
kind: Pod
metadata:
  name: server2
  labels:
    tier: frontend
spec:
  containers:
  - name: hello2
    image: gcr.io/google-samples/hello-app:1.0
